# Generated by Django 4.2.2 on 2023-07-14 16:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_repr', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Kurumsal E-posta')),
                ('address', models.TextField(blank=True, null=True, verbose_name='İş adresi')),
                ('address_link', models.TextField(blank=True, null=True, verbose_name='İş adresi linki')),
            ],
            options={
                'verbose_name': 'Site ayarları',
                'verbose_name_plural': 'Site ayarları',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=64, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
            ],
            options={
                'verbose_name': 'Sıkça sorulan soru',
                'verbose_name_plural': 'Sıkça sorulan sorular',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Medya adı')),
                ('fa_icon', models.CharField(max_length=40, verbose_name='Ikon kodu (Font Awesome)')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Medya hesabı',
                'verbose_name_plural': 'Medya hesapları',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Konum adı')),
                ('link_map', models.URLField(blank=True, null=True, verbose_name='Konum linki')),
            ],
            options={
                'verbose_name': 'Konum',
                'verbose_name_plural': 'Konumlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=55, verbose_name='Name surname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('description', models.TextField(verbose_name='Your message')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Tarih ve saat')),
                ('answered', models.BooleanField(verbose_name='Cevaplandı')),
            ],
            options={
                'verbose_name': 'Talep, Şikayet',
                'verbose_name_plural': 'Talepler ve Şikayetler',
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Kategori adı')),
                ('name_en', models.CharField(max_length=25, null=True, verbose_name='Kategori adı')),
                ('name_tr', models.CharField(max_length=25, null=True, verbose_name='Kategori adı')),
                ('name_de', models.CharField(max_length=25, null=True, verbose_name='Kategori adı')),
                ('name_ru', models.CharField(max_length=25, null=True, verbose_name='Kategori adı')),
            ],
            options={
                'verbose_name': 'Tur kategorisi',
                'verbose_name_plural': 'Tur kategorileri',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TourTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Kategori etiketi')),
                ('name_en', models.CharField(max_length=25, null=True, verbose_name='Kategori etiketi')),
                ('name_tr', models.CharField(max_length=25, null=True, verbose_name='Kategori etiketi')),
                ('name_de', models.CharField(max_length=25, null=True, verbose_name='Kategori etiketi')),
                ('name_ru', models.CharField(max_length=25, null=True, verbose_name='Kategori etiketi')),
            ],
            options={
                'verbose_name': 'Tur etiketi',
                'verbose_name_plural': 'Tur etiketleri',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('pax', models.PositiveIntegerField(verbose_name='Passengers')),
                ('baggage', models.PositiveIntegerField(verbose_name='Baggage (kg)')),
                ('date', models.DateField(verbose_name='Meeting date')),
                ('time', models.TimeField(verbose_name='Meeting time')),
                ('proceed', models.BooleanField(default=False, verbose_name='İncelendi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma tarihi')),
                ('rfrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='transfer.place', verbose_name='From where?')),
                ('rto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to='transfer.place', verbose_name='To where?')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transferler',
                'ordering': ('-date', '-time', 'proceed'),
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Adı')),
            ],
            options={
                'verbose_name': 'Hafta günü',
                'verbose_name_plural': 'Hafta günleri',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TransferExtended',
            fields=[
                ('transfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='transfer.transfer')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fiyat (USD)')),
                ('price_final', models.BooleanField(default=True, verbose_name='Fiyat sonmu?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('back', models.BooleanField(verbose_name='Ek geri dönüş')),
                ('iata', models.CharField(blank=True, max_length=10, null=True, verbose_name='Flight code (IATA)')),
                ('iata_back', models.CharField(blank=True, max_length=10, null=True, verbose_name='Flight code (IATA)')),
                ('date_back', models.DateField(blank=True, null=True, verbose_name='Meeting date')),
                ('time_back', models.TimeField(blank=True, null=True, verbose_name='Meeting time')),
                ('pax_back', models.PositiveIntegerField(blank=True, null=True, verbose_name='Passengers')),
                ('baggage_back', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baggage (kg)')),
                ('first_name', models.CharField(max_length=20, verbose_name='Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Surname')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('done', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('paid', models.BooleanField(default=False, verbose_name='Ödeme yapıldı')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rating')),
            ],
            options={
                'verbose_name': 'Transfer (Gelişmiş)',
                'verbose_name_plural': 'Transferler (Gelişmiş)',
                'ordering': ('-paid', '-date', '-time', 'price'),
            },
            bases=('transfer.transfer', models.Model),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Tur adı')),
                ('name_en', models.CharField(max_length=55, null=True, verbose_name='Tur adı')),
                ('name_tr', models.CharField(max_length=55, null=True, verbose_name='Tur adı')),
                ('name_de', models.CharField(max_length=55, null=True, verbose_name='Tur adı')),
                ('name_ru', models.CharField(max_length=55, null=True, verbose_name='Tur adı')),
                ('excerpt', models.TextField(verbose_name='Kısa açıklama')),
                ('excerpt_en', models.TextField(null=True, verbose_name='Kısa açıklama')),
                ('excerpt_tr', models.TextField(null=True, verbose_name='Kısa açıklama')),
                ('excerpt_de', models.TextField(null=True, verbose_name='Kısa açıklama')),
                ('excerpt_ru', models.TextField(null=True, verbose_name='Kısa açıklama')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('description_en', models.TextField(null=True, verbose_name='Açıklama')),
                ('description_tr', models.TextField(null=True, verbose_name='Açıklama')),
                ('description_de', models.TextField(null=True, verbose_name='Açıklama')),
                ('description_ru', models.TextField(null=True, verbose_name='Açıklama')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='Tur süresi')),
                ('created', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='transfer/tour/image/', verbose_name='Resim')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Video linki')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Başlangıç saati')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Bitiş saati')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.tourcategory', verbose_name='Kategori')),
                ('tags', models.ManyToManyField(blank=True, to='transfer.tourtag')),
                ('weekdays', models.ManyToManyField(blank=True, to='transfer.weekday', verbose_name='Hafta günleri')),
            ],
            options={
                'verbose_name': 'Tur',
                'verbose_name_plural': 'Turlar',
                'ordering': ('name', 'created'),
            },
        ),
    ]
