# Generated by Django 4.2.2 on 2023-07-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_de',
            field=models.TextField(null=True, verbose_name='Cevap'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Cevap'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Cevap'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tr',
            field=models.TextField(null=True, verbose_name='Cevap'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_de',
            field=models.CharField(max_length=64, null=True, verbose_name='Soru'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Soru'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Soru'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tr',
            field=models.CharField(max_length=64, null=True, verbose_name='Soru'),
        ),
        migrations.AddField(
            model_name='weekday',
            name='name_de',
            field=models.CharField(max_length=30, null=True, verbose_name='Adı'),
        ),
        migrations.AddField(
            model_name='weekday',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Adı'),
        ),
        migrations.AddField(
            model_name='weekday',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Adı'),
        ),
        migrations.AddField(
            model_name='weekday',
            name='name_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='request',
            name='answered',
            field=models.BooleanField(default=False, verbose_name='Cevaplandı'),
        ),
    ]
