# Generated by Django 5.1.15 on 2026-01-07 17:18

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='image_head',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=None, force_format=None, keep_meta=True, quality=90, scale=None, size=[1920, 600], upload_to='transfer/excursion/image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excursion',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, scale=None, size=[1024, 724], upload_to='transfer/excursion/image'),
        ),
    ]
