# Generated by Django 4.2.2 on 2023-07-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_faq_answer_de_faq_answer_en_faq_answer_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name_de',
            field=models.CharField(max_length=25, null=True, verbose_name='Konum adı'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_en',
            field=models.CharField(max_length=25, null=True, verbose_name='Konum adı'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_ru',
            field=models.CharField(max_length=25, null=True, verbose_name='Konum adı'),
        ),
        migrations.AddField(
            model_name='place',
            name='name_tr',
            field=models.CharField(max_length=25, null=True, verbose_name='Konum adı'),
        ),
    ]
