# Generated by Django 5.1.15 on 2026-01-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_excursion_image_head_alter_excursion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tur süresi'),
        ),
    ]
