# Generated by Django 4.2.2 on 2023-07-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_place_name_de_place_name_en_place_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Konum adı'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Konum adı'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Konum adı'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Konum adı'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Konum adı'),
        ),
    ]
